apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  containers:
  - image: busybox
    name: secure-pod
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
        add:
        - NET_ADMIN
        - SYS_TIME
