apiVersion: v1
kind: Pod
metadata:
  name: cpu-pod
spec:
  containers:
  - image: vish/stress
    name: cpu-pod
    resources:
      requests:
        cpu: "50m"
      limits:
        cpu: "900m"
    args:
    - -cpus
    - "1"
