apiVersion: v1
kind: Pod
metadata:
  name: backend-app
  namespace: team-blue
  labels:
    app: backend
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: "app"
            operator: In
            values:
            - "frontend"
        topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    tier: backend
  containers:
  - image: busybox
    name: backend-app
    command: ["sleep", "3600"]
  restartPolicy: Never
